const dataSet = [{
  title: '仓储商名称',
  data: 'warehousingDealerName'
}, {
  title: '仓库名称',
  data: 'warehouseName'
}, {
  title: '全局分类',
  data: 'globalCategoryName',
  sort: true
}, {
  title: '主分类',
  data: 'mainCategoryName',
  sort: true
}, {
  title: '子分类',
  data: 'subCategoryName',
  sort: true
}, {
  title: '记账主体',
  data: 'accountingSubjectName',
  sort: true
}, {
  title: '货品编码',
  data: 'goodsCode',
  sort: true
}, {
  title: '货品名称',
  data: 'goodsName',
  sort: true
}, {
  title: '最小使用单位',
  data: 'smallestSellUnitName'
}, {
  title: '组成数量',
  data: 'packageNumber'
}, {
  title: '库存单位（采购单位）',
  data: 'stockUnitName'
}, {
  title: '箱包装数量',
  data: 'boxPackageAmount'
}, {
  title: '箱包装单位（收货单位）',
  data: 'boxPackageUnit'
}, {
  title: '温层',
  data: 'temperatureLayerName'
}, {
  title: '采购在途库存',
  data: 'procurementOnorderInventory'
}, {
  title: '调拨在途库存',
  data: 'reconciliationOnorderInventory'
}]

export { dataSet }
