const dataSet = [{
  title: '仓储商名称',
  data: 'warehousingDealerName'
}, {
  title: '仓库名称',
  data: 'warehouseName'
}, {
  title: '全局分类',
  data: 'globalCategoryName',
  sort: true
}, {
  title: '主分类',
  data: 'mainCategoryName',
  sort: true
}, {
  title: '子分类',
  data: 'subCategoryName',
  sort: true
}, {
  title: '记账主体',
  data: 'accountingSubjectName',
  sort: true
}, {
  title: '货品编码',
  data: 'goodsCode',
  sort: true
}, {
  title: '货品名称',
  data: 'goodsName',
  sort: true
}, {
  title: '最小使用单位',
  data: 'smallestSellUnitName'
}, {
  title: '组成数量',
  data: 'packageNumber'
}, {
  title: '库存单位（采购单位）',
  data: 'stockUnitName'
}, {
  title: '箱包装数量',
  data: 'boxPackageAmount'
}, {
  title: '箱包装单位（收货单位）',
  data: 'boxPackageUnit'
}, {
  title: '温层',
  data: 'temperatureLayerName'
}, {
  title: '采购入库库存',
  data: 'procurementStockinInventory'
}, {
  title: '退货入库库存',
  data: 'returnStockinInventory'
}, {
  title: '调拨入库库存',
  data: 'reconciliationStockinInventory'
}, {
  title: '次品入库库存',
  data: 'substandardStockinInventory'
}, {
  title: '尾料入库库存',
  data: 'tailingStockinInventory'
}, {
  title: '原料返库入库库存',
  data: 'materialStockinInventory'
}, {
  title: '产成品入库库存',
  data: 'productStockinInventory'
}, {
  title: '调拨占用库存',
  data: 'reconciliationOccupyInventory'
}, {
  title: '调拨出库库存',
  data: 'reconciliationStockoutInventory'
}, {
  title: '调拨在途库存',
  data: 'reconciliationOnorderInventory'
}, {
  title: '转移库存',
  data: 'transferInventory'
}, {
  title: '退单占用库存',
  data: 'returnOccupyInventory'
}, {
  title: '退单出库库存',
  data: 'returnStockoutInventory'
}, {
  title: '生产占用库存',
  data: 'processingOccupyInventory'
}, {
  title: '原料库出库库存',
  data: 'materialStockoutInventory'
}, {
  title: '尾料库出库库存',
  data: 'tailingStockoutInventory'
}, {
  title: '可用库存',
  data: 'availableInventory'
}, {
  title: '盘盈盘亏',
  data: 'shortageOverInventory'
}, {
  title: '正品转次品',
  data: 'qualifiedSubstandardInventory'
}, {
  title: '次品转正品',
  data: 'substandardQualifiedInventory'
}, {
  title: '次品库存',
  data: 'substandardInventory'
}]

export { dataSet }
