// 查询表格
const dataSet = [{
  title: '出库单',
  data: 'stockCode'
}, {
  title: '单据类型',
  data: 'stockTypeName'
}, {
  title: '来源单号',
  data: 'sourceCode'
}, {
  title: '来源单类型',
  data: 'sourceType'
}, {
  title: '货品编码',
  data: 'goodsCode'
}, {
  title: '货品名称',
  data: 'goodsName'
}, {
  title: '仓储商名称',
  data: 'warehousingDealerName'
}, {
  title: '仓库名称',
  data: 'targetWarehouseName'
}, {
  title: '批次',
  data: 'batchNo'
}, {
  title: '到效日期',
  data: 'availableDate'
}, {
  title: '到期日期',
  data: 'expirationDate'
}, {
  title: '退单出库数量',
  data: 'amount'
}, {
  title: '出库时间',
  data: 'stockTime'
}, {
  title: '操作',
  data: 'handle'
}]
export { dataSet }
